export const conversations = [
  {
    conversation_id: 1,
    other_user_id: 2,
    user_name: 'Rahul Sharma',
    message: 'I can start working on this tomorrow.',
  },
  {
    conversation_id: 2,
    other_user_id: 3,
    user_name: 'Priya Reddy',
    message: 'Could you send me the project requirements?',
  },
  {
    conversation_id: 3,
    other_user_id: 4,
    user_name: 'Arjun Mehta',
    message: 'Thanks, I will review the proposal.',
  },
  {
    conversation_id: 4,
    other_user_id: 5,
    user_name: 'Sneha Kapoor',
    message: 'The changes have been completed.',
  },
  {
    conversation_id: 5,
    other_user_id: 6,
    user_name: 'Vikram Singh',
    message: 'I have uploaded the latest files.',
  },
  {
    conversation_id: 6,
    other_user_id: 7,
    user_name: 'Ananya Rao',
    message: 'When would you like to schedule the call?',
  },
  {
    conversation_id: 7,
    other_user_id: 8,
    user_name: 'Karan Malhotra',
    message: 'The backend API is ready for testing.',
  },
  {
    conversation_id: 8,
    other_user_id: 9,
    user_name: 'Neha Verma',
    message: 'I will send the updated design tonight.',
  },
  {
    conversation_id: 9,
    other_user_id: 10,
    user_name: 'Aditya Nair',
    message: 'Can we discuss the budget?',
  },
  {
    conversation_id: 10,
    other_user_id: 11,
    user_name: 'Meera Iyer',
    message: 'The client approved the initial design.',
  },
  {
    conversation_id: 11,
    other_user_id: 12,
    user_name: 'Rohan Gupta',
    message: 'I have pushed the changes to GitHub.',
  },
  {
    conversation_id: 12,
    other_user_id: 13,
    user_name: 'Kavya Menon',
    message: 'Please check the updated requirements.',
  },
  {
    conversation_id: 13,
    other_user_id: 14,
    user_name: 'Siddharth Joshi',
    message: 'I can complete this by Friday.',
  },
  {
    conversation_id: 14,
    other_user_id: 15,
    user_name: 'Pooja Agarwal',
    message: 'The payment has been received. Thank you.',
  },
  {
    conversation_id: 15,
    other_user_id: 16,
    user_name: 'Nikhil Bansal',
    message: 'Could you share the database schema?',
  },
  {
    conversation_id: 16,
    other_user_id: 17,
    user_name: 'Ishita Shah',
    message: 'I have finished the mobile responsive layout.',
  },
  {
    conversation_id: 17,
    other_user_id: 18,
    user_name: 'Manish Kumar',
    message: 'Let me know if you need any changes.',
  },
  {
    conversation_id: 18,
    other_user_id: 19,
    user_name: 'Divya Krishnan',
    message: 'The deployment was successful.',
  },
  {
    conversation_id: 19,
    other_user_id: 20,
    user_name: 'Akash Patel',
    message: 'I will look into the issue now.',
  },
  {
    conversation_id: 20,
    other_user_id: 21,
    user_name: 'Aditi Sinha',
    message: 'The project requirements look good.',
  },
  {
    conversation_id: 21,
    other_user_id: 22,
    user_name: 'Varun Desai',
    message: 'Can you review this pull request?',
  },
  {
    conversation_id: 22,
    other_user_id: 23,
    user_name: 'Shreya Das',
    message: 'I have attached the final assets.',
  },
  {
    conversation_id: 23,
    other_user_id: 24,
    user_name: 'Harsh Vardhan',
    message: 'We can discuss this during tomorrow’s meeting.',
  },
  {
    conversation_id: 24,
    other_user_id: 25,
    user_name: 'Nandini Rao',
    message: 'The landing page is almost finished.',
  },
  {
    conversation_id: 25,
    other_user_id: 26,
    user_name: 'Yash Agarwal',
    message: 'I found the issue with the authentication flow.',
  },
  {
    conversation_id: 26,
    other_user_id: 27,
    user_name: 'Riya Chatterjee',
    message: 'Could you provide access to the repository?',
  },
  {
    conversation_id: 27,
    other_user_id: 28,
    user_name: 'Abhishek Jain',
    message: 'I will send you the progress update shortly.',
  },
  {
    conversation_id: 28,
    other_user_id: 29,
    user_name: 'Tanvi Kulkarni',
    message: 'The new version is ready for review.',
  },
  {
    conversation_id: 29,
    other_user_id: 30,
    user_name: 'Mohit Arora',
    message: 'Everything looks good from my side.',
  },
  {
    conversation_id: 30,
    other_user_id: 31,
    user_name: 'Simran Kaur',
    message: 'Thank you, I will get started on it.',
  },
]
